---
root: true

env:
  browser: true
  es2021: true
  jest: true
  node: true
extends:
  - "eslint:recommended"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - json
rules:
  semi:
    - error
    - always
  react/prop-types:
    - off
  no-use-before-define:
    - off
  quotes:
    - error
    - single
  no-unused-vars:
    - off
settings:
  react:
    version: detect
globals:
  window: true
  process: true
  module: true
